/// Categorized occupation options shown in the profile picker
/// (lib/pages/profile/edit/occupation_edit.dart).
///
/// Stored on the server as a single plain-text string — the picker just
/// constrains the values users can submit. None of these strings exceed
/// the 80-char `User.occupation.maxlength` limit.
///
/// Add new options by appending to the relevant category's `options` list.
/// Order within each category is by frequency / familiarity, not alphabet.
library;

class OccupationCategory {
  /// Stable identifier — used as the l10n lookup key (see
  /// `_localizedCategoryName` in occupation_edit.dart). Don't rename
  /// after release; English [name] can be edited freely.
  final String id;

  /// English fallback display name (used if no localization exists or
  /// when listing categories in non-UI contexts).
  final String name;

  final String icon; // single emoji
  final List<String> options;

  const OccupationCategory({
    required this.id,
    required this.name,
    required this.icon,
    required this.options,
  });
}

/// All occupation options, grouped by major industry/sector.
///
/// "Other" / "Prefer not to say" / life-stage entries live in the last
/// category so the picker can render them at the bottom without special-
/// casing.
const List<OccupationCategory> kOccupationCategories = [
  OccupationCategory(
    id: 'tech',
    name: 'Technology & Software',
    icon: '💻',
    options: [
      'Software Engineer',
      'Frontend Developer',
      'Backend Developer',
      'Full-Stack Developer',
      'Mobile Developer',
      'iOS Developer',
      'Android Developer',
      'DevOps Engineer',
      'Site Reliability Engineer',
      'Cloud Architect',
      'Data Scientist',
      'Data Analyst',
      'Data Engineer',
      'Machine Learning Engineer',
      'AI Researcher',
      'Product Manager',
      'UX Designer',
      'UI Designer',
      'QA Engineer',
      'Cybersecurity Specialist',
      'Database Administrator',
      'IT Support',
      'Systems Administrator',
      'Network Engineer',
      'Game Developer',
      'Web Developer',
      'Technical Writer',
    ],
  ),
  OccupationCategory(
    id: 'healthcare',
    name: 'Healthcare & Medicine',
    icon: '⚕️',
    options: [
      'Doctor',
      'Nurse',
      'Surgeon',
      'Dentist',
      'Pharmacist',
      'Veterinarian',
      'Physical Therapist',
      'Occupational Therapist',
      'Psychologist',
      'Psychiatrist',
      'Paramedic',
      'Nutritionist',
      'Dietitian',
      'Optometrist',
      'Chiropractor',
      'Medical Researcher',
      'Lab Technician',
      'Radiologist',
      'Midwife',
      'Caregiver',
    ],
  ),
  OccupationCategory(
    id: 'education',
    name: 'Education & Academia',
    icon: '📚',
    options: [
      'Teacher',
      'Elementary School Teacher',
      'High School Teacher',
      'University Professor',
      'Lecturer',
      'Tutor',
      'Language Teacher',
      'Music Teacher',
      'Sports Coach',
      'Principal',
      'School Counselor',
      'Librarian',
      'Academic Researcher',
      'Teaching Assistant',
      'Early Childhood Educator',
    ],
  ),
  OccupationCategory(
    id: 'business',
    name: 'Business & Finance',
    icon: '💼',
    options: [
      'Accountant',
      'Auditor',
      'Bookkeeper',
      'Tax Specialist',
      'Financial Analyst',
      'Investment Banker',
      'Financial Advisor',
      'Stock Trader',
      'Insurance Agent',
      'Business Analyst',
      'Management Consultant',
      'Operations Manager',
      'HR Manager',
      'Recruiter',
      'Project Manager',
      'Program Manager',
      'Marketing Manager',
      'Brand Manager',
      'Sales Manager',
      'Sales Representative',
      'Business Owner',
      'CEO / Executive',
      'CFO',
      'CTO',
    ],
  ),
  OccupationCategory(
    id: 'creative',
    name: 'Creative & Design',
    icon: '🎨',
    options: [
      'Graphic Designer',
      'Illustrator',
      'Animator',
      'Photographer',
      'Videographer',
      'Video Editor',
      'Filmmaker',
      'Painter',
      'Sculptor',
      'Fashion Designer',
      'Interior Designer',
      'Architect',
      'Industrial Designer',
      'Jewelry Designer',
      'Tattoo Artist',
      'Calligrapher',
      'Art Director',
      'Creative Director',
    ],
  ),
  OccupationCategory(
    id: 'media',
    name: 'Media & Communication',
    icon: '📺',
    options: [
      'Journalist',
      'Reporter',
      'News Anchor',
      'Editor',
      'Writer',
      'Author',
      'Novelist',
      'Poet',
      'Translator',
      'Interpreter',
      'PR Specialist',
      'Marketing Specialist',
      'Social Media Manager',
      'Content Creator',
      'YouTuber',
      'Streamer',
      'Podcaster',
      'Radio Host',
      'Influencer',
      'Copywriter',
    ],
  ),
  OccupationCategory(
    id: 'engineering',
    name: 'Engineering',
    icon: '🛠️',
    options: [
      'Mechanical Engineer',
      'Electrical Engineer',
      'Civil Engineer',
      'Chemical Engineer',
      'Aerospace Engineer',
      'Industrial Engineer',
      'Environmental Engineer',
      'Biomedical Engineer',
      'Petroleum Engineer',
      'Structural Engineer',
      'Marine Engineer',
      'Robotics Engineer',
    ],
  ),
  OccupationCategory(
    id: 'science',
    name: 'Science & Research',
    icon: '🔬',
    options: [
      'Biologist',
      'Chemist',
      'Physicist',
      'Mathematician',
      'Statistician',
      'Astronomer',
      'Geologist',
      'Meteorologist',
      'Marine Biologist',
      'Microbiologist',
      'Zoologist',
      'Anthropologist',
      'Archaeologist',
      'Sociologist',
      'Economist',
      'Researcher',
    ],
  ),
  OccupationCategory(
    id: 'legal',
    name: 'Legal',
    icon: '⚖️',
    options: [
      'Lawyer',
      'Attorney',
      'Judge',
      'Prosecutor',
      'Public Defender',
      'Paralegal',
      'Legal Assistant',
      'Notary',
      'Legal Consultant',
    ],
  ),
  OccupationCategory(
    id: 'hospitality',
    name: 'Hospitality & Food Service',
    icon: '🍽️',
    options: [
      'Chef',
      'Cook',
      'Pastry Chef',
      'Baker',
      'Barista',
      'Bartender',
      'Sommelier',
      'Waiter / Server',
      'Restaurant Manager',
      'Hotel Manager',
      'Receptionist',
      'Concierge',
      'Tour Guide',
      'Flight Attendant',
      'Travel Agent',
      'Event Planner',
      'Wedding Planner',
    ],
  ),
  OccupationCategory(
    id: 'trades',
    name: 'Trades & Skilled Labor',
    icon: '🔧',
    options: [
      'Electrician',
      'Plumber',
      'Carpenter',
      'Mechanic',
      'Welder',
      'Mason',
      'Roofer',
      'HVAC Technician',
      'Locksmith',
      'Painter (House)',
      'Landscaper',
      'Gardener',
    ],
  ),
  OccupationCategory(
    id: 'transport',
    name: 'Transportation & Logistics',
    icon: '🚛',
    options: [
      'Driver',
      'Truck Driver',
      'Bus Driver',
      'Taxi / Rideshare Driver',
      'Delivery Driver',
      'Pilot',
      'Co-Pilot',
      'Flight Engineer',
      'Ship Captain',
      'Sailor',
      'Train Conductor',
      'Logistics Coordinator',
      'Warehouse Worker',
      'Courier',
    ],
  ),
  OccupationCategory(
    id: 'government',
    name: 'Government & Public Service',
    icon: '🏛️',
    options: [
      'Police Officer',
      'Detective',
      'Firefighter',
      'Military / Armed Forces',
      'Diplomat',
      'Government Employee',
      'Politician',
      'Civil Servant',
      'Social Worker',
      'Postal Worker',
      'Customs Officer',
      'Tax Officer',
    ],
  ),
  OccupationCategory(
    id: 'retail',
    name: 'Retail & Customer Service',
    icon: '🛍️',
    options: [
      'Sales Associate',
      'Cashier',
      'Store Manager',
      'Visual Merchandiser',
      'Customer Service Representative',
      'Call Center Agent',
      'Retail Buyer',
    ],
  ),
  OccupationCategory(
    id: 'agriculture',
    name: 'Agriculture & Environment',
    icon: '🌾',
    options: [
      'Farmer',
      'Rancher',
      'Agronomist',
      'Fisherman',
      'Forester',
      'Beekeeper',
      'Winemaker',
      'Park Ranger',
      'Conservationist',
      'Environmental Scientist',
    ],
  ),
  OccupationCategory(
    id: 'sports',
    name: 'Sports & Fitness',
    icon: '⚽',
    options: [
      'Athlete',
      'Professional Player',
      'Personal Trainer',
      'Fitness Instructor',
      'Yoga Instructor',
      'Pilates Instructor',
      'Sports Coach',
      'Referee',
      'Sports Therapist',
    ],
  ),
  OccupationCategory(
    id: 'beauty',
    name: 'Beauty & Personal Care',
    icon: '💇',
    options: [
      'Hairstylist',
      'Barber',
      'Makeup Artist',
      'Esthetician',
      'Nail Technician',
      'Massage Therapist',
      'Spa Manager',
      'Stylist',
    ],
  ),
  OccupationCategory(
    id: 'realEstate',
    name: 'Real Estate & Construction',
    icon: '🏗️',
    options: [
      'Real Estate Agent',
      'Real Estate Broker',
      'Property Manager',
      'Construction Worker',
      'Construction Manager',
      'Site Supervisor',
      'Surveyor',
      'Urban Planner',
    ],
  ),
  OccupationCategory(
    id: 'religion',
    name: 'Religion & Spirituality',
    icon: '🙏',
    options: [
      'Priest',
      'Pastor',
      'Imam',
      'Rabbi',
      'Monk',
      'Nun',
      'Chaplain',
      'Missionary',
    ],
  ),
  OccupationCategory(
    id: 'student',
    name: 'Student',
    icon: '🎓',
    options: [
      'High School Student',
      'College / Undergraduate Student',
      'Graduate Student',
      'PhD Student',
      'Exchange Student',
      'Language Student',
    ],
  ),
  OccupationCategory(
    id: 'other',
    name: 'Other',
    icon: '✨',
    options: [
      'Entrepreneur',
      'Freelancer',
      'Self-Employed',
      'Consultant',
      'Investor',
      'Volunteer',
      'Stay-at-Home Parent',
      'Retired',
      'Between Jobs',
      'Prefer Not to Say',
    ],
  ),
];

/// Flat list of every option across every category — used by the search box
/// to filter without traversing categories repeatedly.
final List<String> kAllOccupationOptions = kOccupationCategories
    .expand((c) => c.options)
    .toList();
