// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoxWxyi2-XgR3r3WaYhQ2rV-vINDNfXio',
    appId: '1:28446912403:web:de389baef4f8da41170266',
    messagingSenderId: '28446912403',
    projectId: 'bananatalk-backend',
    authDomain: 'bananatalk-backend.firebaseapp.com',
    storageBucket: 'bananatalk-backend.firebasestorage.app',
    measurementId: 'G-V647CPY3HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBXSIbd-CExDrMcZH0EpxZ_69Xy3yT3ZA',
    appId: '1:28446912403:android:dddae6b4e716b84b170266',
    messagingSenderId: '28446912403',
    projectId: 'bananatalk-backend',
    storageBucket: 'bananatalk-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Zn1_YU3URc_T1MRqnTaeLqLa8p9gWFQ',
    appId: '1:28446912403:ios:2771a5e722246e95170266',
    messagingSenderId: '28446912403',
    projectId: 'bananatalk-backend',
    storageBucket: 'bananatalk-backend.firebasestorage.app',
    iosBundleId: 'com.bananatalk.bananatalkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Zn1_YU3URc_T1MRqnTaeLqLa8p9gWFQ',
    appId: '1:28446912403:ios:ba542e009b021df2170266',
    messagingSenderId: '28446912403',
    projectId: 'bananatalk-backend',
    storageBucket: 'bananatalk-backend.firebasestorage.app',
    iosBundleId: 'com.example.bananatalkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoxWxyi2-XgR3r3WaYhQ2rV-vINDNfXio',
    appId: '1:28446912403:web:59e54935821313f6170266',
    messagingSenderId: '28446912403',
    projectId: 'bananatalk-backend',
    authDomain: 'bananatalk-backend.firebaseapp.com',
    storageBucket: 'bananatalk-backend.firebasestorage.app',
    measurementId: 'G-LRMHG4DDWH',
  );
}
